// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joelliu/tpns.jce'
// **********************************************************************

package TPNS_PUSH_PROTOCOL;

public final class AppInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TPNS_PUSH_PROTOCOL.AppInfo";
    }

    public String fullClassName()
    {
        return "TPNS_PUSH_PROTOCOL.AppInfo";
    }

    public long accessId = 0;

    public String accessKey = "";

    public long getAccessId()
    {
        return accessId;
    }

    public void  setAccessId(long accessId)
    {
        this.accessId = accessId;
    }

    public String getAccessKey()
    {
        return accessKey;
    }

    public void  setAccessKey(String accessKey)
    {
        this.accessKey = accessKey;
    }

    public AppInfo()
    {
    }

    public AppInfo(long accessId, String accessKey)
    {
        this.accessId = accessId;
        this.accessKey = accessKey;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppInfo t = (AppInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(accessId, t.accessId) && 
            com.qq.taf.jce.JceUtil.equals(accessKey, t.accessKey) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(accessId, 0);
        _os.write(accessKey, 1);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.accessId = (long) _is.read(accessId, 0, true);
        this.accessKey =  _is.readString(1, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(accessId, "accessId");
        _ds.display(accessKey, "accessKey");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(accessId, true);
        _ds.displaySimple(accessKey, false);
    }

}

