// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joelliu/tpns.jce'
// **********************************************************************

package TPNS_PUSH_PROTOCOL;

public final class DeviceInfoHolder
{
    public DeviceInfoHolder()
    {
    }
    public DeviceInfoHolder(DeviceInfo value)
    {
        this.value = value;
    }

    public DeviceInfo value;
}
