// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joelliu/tpns.jce'
// **********************************************************************

package TPNS_PUSH_PROTOCOL;

public final class DeviceInfo extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TPNS_PUSH_PROTOCOL.DeviceInfo";
    }

    public String fullClassName()
    {
        return "TPNS_PUSH_PROTOCOL.DeviceInfo";
    }

    public String imei = "";

    public String model = "";

    public String os = "";

    public String network = "";

    public String sdCard = "";

    public String sdDouble = "";

    public String resolution = "";

    public String manu = "";

    public String apiLevel = "";

    public String getImei()
    {
        return imei;
    }

    public void  setImei(String imei)
    {
        this.imei = imei;
    }

    public String getModel()
    {
        return model;
    }

    public void  setModel(String model)
    {
        this.model = model;
    }

    public String getOs()
    {
        return os;
    }

    public void  setOs(String os)
    {
        this.os = os;
    }

    public String getNetwork()
    {
        return network;
    }

    public void  setNetwork(String network)
    {
        this.network = network;
    }

    public String getSdCard()
    {
        return sdCard;
    }

    public void  setSdCard(String sdCard)
    {
        this.sdCard = sdCard;
    }

    public String getSdDouble()
    {
        return sdDouble;
    }

    public void  setSdDouble(String sdDouble)
    {
        this.sdDouble = sdDouble;
    }

    public String getResolution()
    {
        return resolution;
    }

    public void  setResolution(String resolution)
    {
        this.resolution = resolution;
    }

    public String getManu()
    {
        return manu;
    }

    public void  setManu(String manu)
    {
        this.manu = manu;
    }

    public String getApiLevel()
    {
        return apiLevel;
    }

    public void  setApiLevel(String apiLevel)
    {
        this.apiLevel = apiLevel;
    }

    public DeviceInfo()
    {
    }

    public DeviceInfo(String imei, String model, String os, String network, String sdCard, String sdDouble, String resolution, String manu, String apiLevel)
    {
        this.imei = imei;
        this.model = model;
        this.os = os;
        this.network = network;
        this.sdCard = sdCard;
        this.sdDouble = sdDouble;
        this.resolution = resolution;
        this.manu = manu;
        this.apiLevel = apiLevel;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        DeviceInfo t = (DeviceInfo) o;
        return (
            com.qq.taf.jce.JceUtil.equals(imei, t.imei) && 
            com.qq.taf.jce.JceUtil.equals(model, t.model) && 
            com.qq.taf.jce.JceUtil.equals(os, t.os) && 
            com.qq.taf.jce.JceUtil.equals(network, t.network) && 
            com.qq.taf.jce.JceUtil.equals(sdCard, t.sdCard) && 
            com.qq.taf.jce.JceUtil.equals(sdDouble, t.sdDouble) && 
            com.qq.taf.jce.JceUtil.equals(resolution, t.resolution) && 
            com.qq.taf.jce.JceUtil.equals(manu, t.manu) && 
            com.qq.taf.jce.JceUtil.equals(apiLevel, t.apiLevel) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        if (null != imei)
        {
            _os.write(imei, 0);
        }
        if (null != model)
        {
            _os.write(model, 1);
        }
        if (null != os)
        {
            _os.write(os, 2);
        }
        if (null != network)
        {
            _os.write(network, 3);
        }
        if (null != sdCard)
        {
            _os.write(sdCard, 4);
        }
        if (null != sdDouble)
        {
            _os.write(sdDouble, 5);
        }
        if (null != resolution)
        {
            _os.write(resolution, 6);
        }
        if (null != manu)
        {
            _os.write(manu, 7);
        }
        if (null != apiLevel)
        {
            _os.write(apiLevel, 8);
        }
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.imei =  _is.readString(0, false);
        this.model =  _is.readString(1, false);
        this.os =  _is.readString(2, false);
        this.network =  _is.readString(3, false);
        this.sdCard =  _is.readString(4, false);
        this.sdDouble =  _is.readString(5, false);
        this.resolution =  _is.readString(6, false);
        this.manu =  _is.readString(7, false);
        this.apiLevel =  _is.readString(8, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(imei, "imei");
        _ds.display(model, "model");
        _ds.display(os, "os");
        _ds.display(network, "network");
        _ds.display(sdCard, "sdCard");
        _ds.display(sdDouble, "sdDouble");
        _ds.display(resolution, "resolution");
        _ds.display(manu, "manu");
        _ds.display(apiLevel, "apiLevel");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(imei, true);
        _ds.displaySimple(model, true);
        _ds.displaySimple(os, true);
        _ds.displaySimple(network, true);
        _ds.displaySimple(sdCard, true);
        _ds.displaySimple(sdDouble, true);
        _ds.displaySimple(resolution, true);
        _ds.displaySimple(manu, true);
        _ds.displaySimple(apiLevel, false);
    }

}

