// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joelliu/tpns.jce'
// **********************************************************************

package TPNS_PUSH_PROTOCOL;

public final class NotifyMsg extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TPNS_PUSH_PROTOCOL.NotifyMsg";
    }

    public String fullClassName()
    {
        return "TPNS_PUSH_PROTOCOL.NotifyMsg";
    }

    public String title = "";

    public String content = "";

    public String sound = "";

    public short lightOn = 0;

    public short vibrateOn = 0;

    public String getTitle()
    {
        return title;
    }

    public void  setTitle(String title)
    {
        this.title = title;
    }

    public String getContent()
    {
        return content;
    }

    public void  setContent(String content)
    {
        this.content = content;
    }

    public String getSound()
    {
        return sound;
    }

    public void  setSound(String sound)
    {
        this.sound = sound;
    }

    public short getLightOn()
    {
        return lightOn;
    }

    public void  setLightOn(short lightOn)
    {
        this.lightOn = lightOn;
    }

    public short getVibrateOn()
    {
        return vibrateOn;
    }

    public void  setVibrateOn(short vibrateOn)
    {
        this.vibrateOn = vibrateOn;
    }

    public NotifyMsg()
    {
    }

    public NotifyMsg(String title, String content, String sound, short lightOn, short vibrateOn)
    {
        this.title = title;
        this.content = content;
        this.sound = sound;
        this.lightOn = lightOn;
        this.vibrateOn = vibrateOn;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        NotifyMsg t = (NotifyMsg) o;
        return (
            com.qq.taf.jce.JceUtil.equals(title, t.title) && 
            com.qq.taf.jce.JceUtil.equals(content, t.content) && 
            com.qq.taf.jce.JceUtil.equals(sound, t.sound) && 
            com.qq.taf.jce.JceUtil.equals(lightOn, t.lightOn) && 
            com.qq.taf.jce.JceUtil.equals(vibrateOn, t.vibrateOn) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(title, 0);
        _os.write(content, 1);
        if (null != sound)
        {
            _os.write(sound, 2);
        }
        _os.write(lightOn, 3);
        _os.write(vibrateOn, 4);
    }


    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.title =  _is.readString(0, true);
        this.content =  _is.readString(1, true);
        this.sound =  _is.readString(2, false);
        this.lightOn = (short) _is.read(lightOn, 3, false);
        this.vibrateOn = (short) _is.read(vibrateOn, 4, false);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(title, "title");
        _ds.display(content, "content");
        _ds.display(sound, "sound");
        _ds.display(lightOn, "lightOn");
        _ds.display(vibrateOn, "vibrateOn");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(title, true);
        _ds.displaySimple(content, true);
        _ds.displaySimple(sound, true);
        _ds.displaySimple(lightOn, true);
        _ds.displaySimple(vibrateOn, false);
    }

}

