// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joelliu/tpns.jce'
// **********************************************************************

package TPNS_PUSH_PROTOCOL;

public final class TpnsPushReq extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TPNS_PUSH_PROTOCOL.TpnsPushReq";
    }

    public String fullClassName()
    {
        return "TPNS_PUSH_PROTOCOL.TpnsPushReq";
    }

    public long accessId = 0;

    public TPNS_PUSH_PROTOCOL.UUID msgId = null;

    public String token = "";

    public TPNS_PUSH_PROTOCOL.TpnsPushPayload payload = null;

    public String activity = "";

    public long getAccessId()
    {
        return accessId;
    }

    public void  setAccessId(long accessId)
    {
        this.accessId = accessId;
    }

    public TPNS_PUSH_PROTOCOL.UUID getMsgId()
    {
        return msgId;
    }

    public void  setMsgId(TPNS_PUSH_PROTOCOL.UUID msgId)
    {
        this.msgId = msgId;
    }

    public String getToken()
    {
        return token;
    }

    public void  setToken(String token)
    {
        this.token = token;
    }

    public TPNS_PUSH_PROTOCOL.TpnsPushPayload getPayload()
    {
        return payload;
    }

    public void  setPayload(TPNS_PUSH_PROTOCOL.TpnsPushPayload payload)
    {
        this.payload = payload;
    }

    public String getActivity()
    {
        return activity;
    }

    public void  setActivity(String activity)
    {
        this.activity = activity;
    }

    public TpnsPushReq()
    {
    }

    public TpnsPushReq(long accessId, TPNS_PUSH_PROTOCOL.UUID msgId, String token, TPNS_PUSH_PROTOCOL.TpnsPushPayload payload, String activity)
    {
        this.accessId = accessId;
        this.msgId = msgId;
        this.token = token;
        this.payload = payload;
        this.activity = activity;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        TpnsPushReq t = (TpnsPushReq) o;
        return (
            com.qq.taf.jce.JceUtil.equals(accessId, t.accessId) && 
            com.qq.taf.jce.JceUtil.equals(msgId, t.msgId) && 
            com.qq.taf.jce.JceUtil.equals(token, t.token) && 
            com.qq.taf.jce.JceUtil.equals(payload, t.payload) && 
            com.qq.taf.jce.JceUtil.equals(activity, t.activity) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(accessId, 0);
        _os.write(msgId, 1);
        _os.write(token, 2);
        _os.write(payload, 3);
        _os.write(activity, 4);
    }

    static TPNS_PUSH_PROTOCOL.UUID cache_msgId;
    static TPNS_PUSH_PROTOCOL.TpnsPushPayload cache_payload;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        this.accessId = (long) _is.read(accessId, 0, true);
        if(null == cache_msgId)
        {
            cache_msgId = new TPNS_PUSH_PROTOCOL.UUID();
        }
        this.msgId = (TPNS_PUSH_PROTOCOL.UUID) _is.read(cache_msgId, 1, true);
        this.token =  _is.readString(2, true);
        if(null == cache_payload)
        {
            cache_payload = new TPNS_PUSH_PROTOCOL.TpnsPushPayload();
        }
        this.payload = (TPNS_PUSH_PROTOCOL.TpnsPushPayload) _is.read(cache_payload, 3, true);
        this.activity =  _is.readString(4, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(accessId, "accessId");
        _ds.display(msgId, "msgId");
        _ds.display(token, "token");
        _ds.display(payload, "payload");
        _ds.display(activity, "activity");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(accessId, true);
        _ds.displaySimple(msgId, true);
        _ds.displaySimple(token, true);
        _ds.displaySimple(payload, true);
        _ds.displaySimple(activity, false);
    }

}

