// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joelliu/tpns.jce'
// **********************************************************************

package TPNS_PUSH_PROTOCOL;

public final class TPNS_MSG_TYPE implements java.io.Serializable
{
    private static TPNS_MSG_TYPE[] __values = new TPNS_MSG_TYPE[2];
    private int __value;
    private String __T = new String();

    public static final int _TYPE_NOTIFY = 0;
    public static final TPNS_MSG_TYPE TYPE_NOTIFY = new TPNS_MSG_TYPE(0,_TYPE_NOTIFY,"TYPE_NOTIFY");
    public static final int _TYPE_TRANSPARENT = 1;
    public static final TPNS_MSG_TYPE TYPE_TRANSPARENT = new TPNS_MSG_TYPE(1,_TYPE_TRANSPARENT,"TYPE_TRANSPARENT");

    public static TPNS_MSG_TYPE convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static TPNS_MSG_TYPE convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private TPNS_MSG_TYPE(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
