// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.5.7 by WSRD Tencent.
// Generated from `/usr/local/resin_system.mqq.com/webapps/communication/taf/upload/joelliu/tpns.jce'
// **********************************************************************

package TPNS_PUSH_PROTOCOL;

public final class UUID extends com.qq.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "TPNS_PUSH_PROTOCOL.UUID";
    }

    public String fullClassName()
    {
        return "TPNS_PUSH_PROTOCOL.UUID";
    }

    public byte [] bits = null;

    public byte [] getBits()
    {
        return bits;
    }

    public void  setBits(byte [] bits)
    {
        this.bits = bits;
    }

    public UUID()
    {
    }

    public UUID(byte [] bits)
    {
        this.bits = bits;
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        UUID t = (UUID) o;
        return (
            com.qq.taf.jce.JceUtil.equals(bits, t.bits) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.qq.taf.jce.JceOutputStream _os)
    {
        _os.write(bits, 0);
    }

    static byte [] cache_bits;

    public void readFrom(com.qq.taf.jce.JceInputStream _is)
    {
        if(null == cache_bits)
        {
            cache_bits = (byte[]) new byte[1];
            byte __var_1 = 0;
            ((byte[])cache_bits)[0] = __var_1;
        }
        this.bits = (byte []) _is.read(cache_bits, 0, true);
    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.display(bits, "bits");
    }

    public void displaySimple(java.lang.StringBuilder _os, int _level)
    {
        com.qq.taf.jce.JceDisplayer _ds = new com.qq.taf.jce.JceDisplayer(_os, _level);
        _ds.displaySimple(bits, false);
    }

}

